import { NextResponse } from "next/server";
import { appendAuditEvent, now, readStore, writeStore } from "@/lib/platform/store";

function reportFileName(reportId: string, ext: "json" | "html"): string {
  return `lexnet-report-${reportId}.${ext}`;
}

function reportHtml(report: any): string {
  const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const verdictColor = report.verdict === "approved" ? "#059669" : "#DC2626";
  const verdictBg = report.verdict === "approved" ? "#ECFDF5" : "#FEF2F2";
  return `<!doctype html><html><head><meta charset="utf-8"><title>LexNet Report ${esc(report.id)}</title>
<style>
  @page{margin:1in}@media print{body{margin:0}}
  body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;max-width:800px;margin:0 auto;padding:48px;color:#111827;line-height:1.6}
  h1{font-size:24px;font-weight:700;border-bottom:2px solid #E5E7EB;padding-bottom:12px;margin-bottom:24px}
  .badge{display:inline-block;padding:4px 12px;border-radius:999px;font-size:12px;font-weight:600;background:${verdictBg};color:${verdictColor};border:1px solid ${verdictColor}33}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:20px 0}
  .card{padding:16px;border-radius:8px;background:#F8FAFC;border:1px solid #E2E8F0}
  .card .label{font-size:11px;color:#64748B;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:4px}
  .card .value{font-size:18px;font-weight:700}
  .section{margin:24px 0}
  .section h2{font-size:14px;color:#475569;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:12px}
  .rationale{padding:16px;background:#F8FAFC;border-radius:8px;border:1px solid #E2E8F0;font-size:14px;line-height:1.7}
  .footer{margin-top:48px;padding-top:16px;border-top:1px solid #E5E7EB;font-size:11px;color:#94A3B8}
  @media print{.no-print{display:none}}
</style></head><body>
<h1>LexNet Verification Report</h1>
<p style="color:#64748B;font-size:13px;margin-top:-16px;margin-bottom:24px">Report ID: ${esc(report.id)} &middot; Case: ${esc(report.caseId)}</p>

<div class="grid">
  <div class="card"><div class="label">Verdict</div><div class="value"><span class="badge">${esc(report.verdict || "N/A").toUpperCase()}</span></div></div>
  <div class="card"><div class="label">Impact Score</div><div class="value" style="color:${report.impactScore >= 60 ? "#059669" : "#DC2626"}">${report.impactScore}/100</div></div>
  <div class="card"><div class="label">Schema Version</div><div class="value">${esc(report.version || "N/A")} v${report.schemaVersion || 1}</div></div>
  <div class="card"><div class="label">Settlement</div><div class="value" style="font-size:14px">${esc((report.settlementRecommendation || "N/A").replace(/_/g, " "))}</div></div>
</div>

<div class="section"><h2>Rationale</h2><div class="rationale">${esc(report.rationale || "No rationale provided.")}</div></div>

${report.reviewerNotes ? `<div class="section"><h2>Reviewer Notes</h2><div class="rationale">${esc(report.reviewerNotes)}</div></div>` : ""}

<div class="section"><h2>Evidence</h2>
  <p style="font-size:13px;color:#64748B">${(report.evidenceIds || []).length} evidence item(s) reviewed &middot; ${(report.evidenceChecksums || []).length} checksum(s) verified</p>
</div>

<div class="footer">
  <p>Generated by LexNet AI-Arbitrated Escrow Protocol &middot; ${esc(report.createdAt || new Date().toISOString())}</p>
  <p class="no-print" style="margin-top:8px"><button onclick="window.print()" style="padding:8px 20px;border-radius:6px;border:1px solid #D1D5DB;background:white;cursor:pointer;font-size:13px">Save as PDF</button></p>
</div>
</body></html>`;
}

export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const format = new URL(request.url).searchParams.get("format") || "json";
  const store = await readStore();
  const reports = store.reports.filter((entry) => entry.caseId === id);
  const latest = reports.at(-1);
  if (!latest) return NextResponse.json({ error: "Report not found" }, { status: 404 });

  if (format === "download" || format === "print") {
    const { withAuth } = await import("@/lib/platform/route-helpers");
    return withAuth(request, async (userId, address) => {
      latest.status = "exported";
      latest.exportedAt = now();
      await appendAuditEvent(store, {
        workspaceId: latest.workspaceId,
        caseId: id,
        actor: address,
        action: "report.exported",
        payload: { reportId: latest.id, format },
      });
      await writeStore(store);

      if (format === "print") {
        return new NextResponse(reportHtml(latest), {
          headers: {
            "Content-Type": "text/html; charset=utf-8",
            "Content-Disposition": `inline; filename="${reportFileName(latest.id, "html")}"`,
          },
        });
      }

      return new NextResponse(JSON.stringify(latest, null, 2), {
        headers: {
          "Content-Type": "application/json; charset=utf-8",
          "Content-Disposition": `attachment; filename="${reportFileName(latest.id, "json")}"`,
        },
      });
    });
  }

  return NextResponse.json({ report: latest });
}

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { withAuth } = await import("@/lib/platform/route-helpers");
  const { id } = await params;

  return withAuth(request, async (userId, address) => {
    const body = await request.json().catch(() => null) as { status?: "draft" | "reviewed"; reviewerNotes?: string; actor?: string } | null;
    const store = await readStore();
    const reports = store.reports.filter((entry) => entry.caseId === id);
    const latest = reports.at(-1);
    if (!latest) return NextResponse.json({ error: "Report not found" }, { status: 404 });

    if (body?.status) latest.status = body.status;
    if (typeof body?.reviewerNotes === "string") latest.reviewerNotes = body.reviewerNotes.slice(0, 2000);
    await appendAuditEvent(store, {
      workspaceId: latest.workspaceId,
      caseId: id,
      actor: address,
      action: "report.reviewed",
      payload: { reportId: latest.id, status: latest.status },
    });
    await writeStore(store);

    return NextResponse.json({ report: latest });
  });
}
