// ValidatorWallet ABI for querying and managing validator wallet
export const VALIDATOR_WALLET_ABI = [
  // Custom errors
  {name: "NotOperator", type: "error", inputs: []},
  {name: "InvalidAddress", type: "error", inputs: []},
  {name: "TransferFailed", type: "error", inputs: []},
  {name: "OperatorTransferNotReady", type: "error", inputs: []},
  {name: "NoPendingOperator", type: "error", inputs: []},
  // OpenZeppelin Ownable errors
  {name: "OwnableUnauthorizedAccount", type: "error", inputs: [{name: "account", type: "address"}]},
  {name: "OwnableInvalidOwner", type: "error", inputs: [{name: "owner", type: "address"}]},

  // Functions
  {
    name: "operator",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address"}],
  },
  {
    name: "owner",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address"}],
  },
  {
    name: "getIdentity",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          {name: "moniker", type: "string"},
          {name: "logoUri", type: "string"},
          {name: "website", type: "string"},
          {name: "description", type: "string"},
          {name: "email", type: "string"},
          {name: "twitter", type: "string"},
          {name: "telegram", type: "string"},
          {name: "github", type: "string"},
          {name: "extraCid", type: "bytes"},
        ],
      },
    ],
  },
  {
    name: "setOperator",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_operator", type: "address"}],
    outputs: [],
  },
  {
    name: "setIdentity",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "moniker", type: "string"},
      {name: "logoUri", type: "string"},
      {name: "website", type: "string"},
      {name: "description", type: "string"},
      {name: "email", type: "string"},
      {name: "twitter", type: "string"},
      {name: "telegram", type: "string"},
      {name: "github", type: "string"},
      {name: "extraCid", type: "bytes"},
    ],
    outputs: [],
  },
  // Staking functions (forwarded to staking contract)
  {
    name: "validatorDeposit",
    type: "function",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    name: "validatorExit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_shares", type: "uint256"}],
    outputs: [],
  },
  {
    name: "validatorClaim",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  // Two-step operator transfer
  {
    name: "initiateOperatorTransfer",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_newOperator", type: "address"}],
    outputs: [],
  },
  {
    name: "completeOperatorTransfer",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "cancelOperatorTransfer",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "getPendingOperator",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {name: "", type: "address"},
      {name: "", type: "uint256"},
    ],
  },
  {
    name: "getOperator",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address"}],
  },
] as const;

export const STAKING_ABI = [
  // Custom errors from IGenLayerStaking
  {name: "BurnTransferFailed", type: "error", inputs: []},
  {name: "DeepthoughtCallFailed", type: "error", inputs: []},
  {name: "DelegatorBelowMinimumStake", type: "error", inputs: []},
  {name: "DelegatorExitExceedsShares", type: "error", inputs: []},
  {name: "DelegatorExitWouldBeBelowMinimum", type: "error", inputs: []},
  {name: "DelegatorMayNotJoinTwoValidatorsSimultaneously", type: "error", inputs: []},
  {name: "DelegatorMayNotJoinWithZeroValue", type: "error", inputs: []},
  {name: "DelegatorMustExitAllWhenBelowMinimum", type: "error", inputs: []},
  {name: "EpochAdvanceNotReady", type: "error", inputs: []},
  {name: "EpochAlreadyFinalized", type: "error", inputs: []},
  {name: "EpochNotFinalized", type: "error", inputs: []},
  {name: "EpochNotFinished", type: "error", inputs: []},
  {name: "FailedTransfer", type: "error", inputs: [{name: "validator", type: "address"}]},
  {name: "InflationAlreadyInitialized", type: "error", inputs: []},
  {name: "InflationAlreadyReceived", type: "error", inputs: []},
  {name: "InflationInvalidAmount", type: "error", inputs: []},
  {name: "InsufficientInflationFunds", type: "error", inputs: []},
  {name: "InvalidAtEpoch", type: "error", inputs: []},
  {name: "InvalidOperatorAddress", type: "error", inputs: []},
  {name: "MaxNumberOfValidatorsReached", type: "error", inputs: []},
  {name: "MaxValidatorsCannotBeZero", type: "error", inputs: []},
  {name: "NFTMinterCallFailed", type: "error", inputs: []},
  {name: "NFTMinterNotConfigured", type: "error", inputs: []},
  {name: "NoBurning", type: "error", inputs: []},
  {name: "NumberOfValidatorsExceedsAvailable", type: "error", inputs: []},
  {name: "OnlyGEN", type: "error", inputs: []},
  {name: "OnlyIdleness", type: "error", inputs: []},
  {name: "OnlyIdlenessOrTribunal", type: "error", inputs: []},
  {name: "OnlyTransactions", type: "error", inputs: []},
  {name: "OnlyTransactionsOrTribunal", type: "error", inputs: []},
  {name: "OnlyTribunal", type: "error", inputs: []},
  {name: "OperatorAlreadyAssigned", type: "error", inputs: []},
  {name: "PendingTribunals", type: "error", inputs: [{name: "epoch", type: "uint256"}]},
  {name: "PreviousEpochNotFinalizable", type: "error", inputs: []},
  {name: "ReductionFactorCannotBeZero", type: "error", inputs: []},
  {name: "ValidatorAlreadyJoined", type: "error", inputs: []},
  {name: "ValidatorBelowMinimumStake", type: "error", inputs: []},
  {name: "ValidatorExitExceedsShares", type: "error", inputs: []},
  {name: "ValidatorMayNotBeDelegator", type: "error", inputs: []},
  {name: "ValidatorMayNotDepositZeroValue", type: "error", inputs: []},
  {name: "ValidatorMayNotJoinWithZeroValue", type: "error", inputs: []},
  {name: "ValidatorMustNotBeDelegator", type: "error", inputs: []},
  {name: "ValidatorNotActive", type: "error", inputs: []},
  {name: "ValidatorNotJoined", type: "error", inputs: []},
  {name: "ValidatorWithdrawalExceedsStake", type: "error", inputs: []},
  {name: "ValidatorsConsumed", type: "error", inputs: []},
  {name: "ValidatorsUnavailable", type: "error", inputs: []},

  // Events
  {
    name: "AllValidatorBansRemoved",
    type: "event",
    inputs: [],
  },
  {
    name: "BurnFailed",
    type: "event",
    inputs: [
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "BurnToL1",
    type: "event",
    inputs: [
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "DelegatorClaim",
    type: "event",
    inputs: [
      {name: "delegator", type: "address", indexed: false},
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "DelegatorExit",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "delegator", type: "address", indexed: false},
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "DelegatorJoin",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "delegator", type: "address", indexed: false},
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "EpochAdvance",
    type: "event",
    inputs: [
      {name: "epoch", type: "uint256", indexed: false},
    ],
  },
  {
    name: "EpochFinalize",
    type: "event",
    inputs: [
      {name: "epoch", type: "uint256", indexed: false},
    ],
  },
  {
    name: "EpochHasPendingTribunals",
    type: "event",
    inputs: [
      {name: "epoch", type: "uint256", indexed: false},
    ],
  },
  {
    name: "EpochZeroEnded",
    type: "event",
    inputs: [
      {name: "timestamp", type: "uint256", indexed: false},
    ],
  },
  {
    name: "FeesReceived",
    type: "event",
    inputs: [
      {name: "sender", type: "address", indexed: true},
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "InflationInitiated",
    type: "event",
    inputs: [
      {name: "timestamp", type: "uint256", indexed: false},
    ],
  },
  {
    name: "InflationReceived",
    type: "event",
    inputs: [
      {name: "amount", type: "uint256", indexed: false},
      {name: "epoch", type: "uint256", indexed: false},
    ],
  },
  {
    name: "QuarantinesCleanedUp",
    type: "event",
    inputs: [
      {name: "startIndex", type: "uint256", indexed: false},
      {name: "processedCount", type: "uint256", indexed: false},
      {name: "nextIndex", type: "uint256", indexed: false},
    ],
  },
  {
    name: "SetDeepthought",
    type: "event",
    inputs: [
      {name: "deepthought", type: "address", indexed: false},
    ],
  },
  {
    name: "SetDelegatorMinimumStake",
    type: "event",
    inputs: [
      {name: "delegatorMinStake", type: "uint256", indexed: false},
    ],
  },
  {
    name: "SetEpochMinDuration",
    type: "event",
    inputs: [
      {name: "epochMinDuration", type: "uint256", indexed: false},
    ],
  },
  {
    name: "SetEpochMinDurationThreshold",
    type: "event",
    inputs: [
      {name: "epochMinDurationThreshold", type: "uint256", indexed: false},
    ],
  },
  {
    name: "SetEpochZeroMinDuration",
    type: "event",
    inputs: [
      {name: "epochZeroMinDuration", type: "uint256", indexed: false},
    ],
  },
  {
    name: "SetGen",
    type: "event",
    inputs: [
      {name: "gen", type: "address", indexed: false},
    ],
  },
  {
    name: "SetMaxValidators",
    type: "event",
    inputs: [
      {name: "maxValidators", type: "uint256", indexed: false},
    ],
  },
  {
    name: "SetReductionFactor",
    type: "event",
    inputs: [
      {name: "reductionFactor", type: "uint256", indexed: false},
    ],
  },
  {
    name: "SetStakingInvariant",
    type: "event",
    inputs: [
      {name: "stakingInvariant", type: "address", indexed: false},
    ],
  },
  {
    name: "SetTransactionFeesManager",
    type: "event",
    inputs: [
      {name: "transactionFeesManager", type: "address", indexed: false},
    ],
  },
  {
    name: "SetUnbondingPeriods",
    type: "event",
    inputs: [
      {name: "delegatorUnbondingPeriod", type: "uint256", indexed: false},
      {name: "validatorUnbondingPeriod", type: "uint256", indexed: false},
    ],
  },
  {
    name: "SetValidatorMinimumStake",
    type: "event",
    inputs: [
      {name: "validatorMinStake", type: "uint256", indexed: false},
    ],
  },
  {
    name: "SetValidatorWeightParams",
    type: "event",
    inputs: [
      {name: "alpha", type: "uint256", indexed: false},
      {name: "beta", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorBanRemoved",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
    ],
  },
  {
    name: "ValidatorBannedDeterministic",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
    ],
  },
  {
    name: "ValidatorBannedIdleness",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "bannedAt", type: "uint256", indexed: false},
      {name: "bannedUntil", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorClaim",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorDeposit",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorExit",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorJoin",
    type: "event",
    inputs: [
      {name: "operator", type: "address", indexed: false},
      {name: "validator", type: "address", indexed: false},
      {name: "amount", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorPrime",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "epoch", type: "uint256", indexed: false},
      {name: "validatorRewards", type: "uint256", indexed: false},
      {name: "delegatorRewards", type: "uint256", indexed: false},
      {name: "feeRewards", type: "uint256", indexed: false},
      {name: "feePenalties", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorQuarantineRemoved",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
    ],
  },
  {
    name: "ValidatorQuarantineRepealed",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
    ],
  },
  {
    name: "ValidatorQuarantined",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "quarantinedAt", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorSlash",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: false},
      {name: "validatorSlashing", type: "uint256", indexed: false},
      {name: "delegatorSlashing", type: "uint256", indexed: false},
      {name: "epoch", type: "uint256", indexed: false},
    ],
  },
  {
    name: "ValidatorsRegistered",
    type: "event",
    inputs: [
      {name: "count", type: "uint256", indexed: false},
    ],
  },

  // Functions
  {
    name: "activeValidators",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address[]"}],
  },
  {
    name: "activeValidatorsCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "activeWeights",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256[]"}],
  },
  {
    name: "adminRegisterValidators",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "validatorAddresses", type: "address[]"}],
    outputs: [],
  },
  {
    name: "burning",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "canAdvance",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "bool"}],
  },
  {
    name: "deepthoughtInflation",
    type: "function",
    stateMutability: "pure",
    inputs: [{name: "_inflation", type: "uint256"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "delegatorClaim",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [],
  },
  {
    name: "delegatorDeposit",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
      {name: "_index", type: "uint256"},
    ],
    outputs: [
      {
        name: "claim_",
        type: "tuple",
        components: [
          {name: "quantity", type: "uint256"},
          {name: "commit", type: "uint256"},
        ],
      },
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "delegatorDepositByEpoch",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
      {name: "_epoch", type: "uint256"},
    ],
    outputs: [
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "delegatorDepositLen",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "delegatorExit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_amount", type: "uint256"},
    ],
    outputs: [],
  },
  {
    name: "delegatorJoin",
    type: "function",
    stateMutability: "payable",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [],
  },
  {
    name: "delegatorWithdrawal",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
      {name: "_index", type: "uint256"},
    ],
    outputs: [
      {
        name: "claim_",
        type: "tuple",
        components: [
          {name: "quantity", type: "uint256"},
          {name: "commit", type: "uint256"},
        ],
      },
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "delegatorWithdrawalByEpoch",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
      {name: "_epoch", type: "uint256"},
    ],
    outputs: [
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "delegatorWithdrawalLen",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "developerInflation",
    type: "function",
    stateMutability: "pure",
    inputs: [{name: "_inflation", type: "uint256"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "epoch",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "epochAdvance",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "epochEven",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {name: "start", type: "uint256"},
      {name: "end", type: "uint256"},
      {name: "inflation", type: "uint256"},
      {name: "weight", type: "uint256"},
      {name: "weightDeposit", type: "uint256"},
      {name: "weightWithdrawal", type: "uint256"},
      {name: "vcount", type: "uint256"},
      {name: "claimed", type: "uint256"},
      {name: "stakeDeposit", type: "uint256"},
      {name: "stakeWithdrawal", type: "uint256"},
      {name: "slashed", type: "uint256"},
    ],
  },
  {
    name: "epochFinalize",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "epochFinalizeImmediate",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "epochInflation",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_epoch", type: "uint256"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "epochMinDuration",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "epochOdd",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {name: "start", type: "uint256"},
      {name: "end", type: "uint256"},
      {name: "inflation", type: "uint256"},
      {name: "weight", type: "uint256"},
      {name: "weightDeposit", type: "uint256"},
      {name: "weightWithdrawal", type: "uint256"},
      {name: "vcount", type: "uint256"},
      {name: "claimed", type: "uint256"},
      {name: "stakeDeposit", type: "uint256"},
      {name: "stakeWithdrawal", type: "uint256"},
      {name: "slashed", type: "uint256"},
    ],
  },
  {
    name: "epochZeroMinDuration",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "finalized",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "getActivatorForSeed",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_randomSeed", type: "bytes32"},
      {name: "_txCreatedTimestamp", type: "uint256"},
    ],
    outputs: [{name: "", type: "address"}],
  },
  {
    name: "getAllBannedValidators",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_startIndex", type: "uint256"},
      {name: "_size", type: "uint256"},
    ],
    outputs: [
      {
        name: "validatorList",
        type: "tuple[]",
        components: [
          {name: "validator", type: "address"},
          {name: "untilEpochBanned", type: "uint256"},
          {name: "permanentlyBanned", type: "bool"},
        ],
      },
    ],
  },
  {
    name: "getAllBannedValidatorsForEpoch",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_epoch", type: "uint256"},
      {name: "_startIndex", type: "uint256"},
      {name: "_size", type: "uint256"},
    ],
    outputs: [
      {
        name: "validatorList",
        type: "tuple[]",
        components: [
          {name: "validator", type: "address"},
          {name: "untilEpochBanned", type: "uint256"},
          {name: "permanentlyBanned", type: "bool"},
        ],
      },
    ],
  },
  {
    name: "getAllQuarantinedValidators",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_startIndex", type: "uint256"},
      {name: "_size", type: "uint256"},
    ],
    outputs: [
      {
        name: "validatorList",
        type: "tuple[]",
        components: [
          {name: "validator", type: "address"},
          {name: "untilEpochBanned", type: "uint256"},
          {name: "permanentlyBanned", type: "bool"},
        ],
      },
    ],
  },
  {
    name: "getAllQuarantinedValidatorsForEpoch",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_epoch", type: "uint256"},
      {name: "_startIndex", type: "uint256"},
      {name: "_size", type: "uint256"},
    ],
    outputs: [
      {
        name: "validatorList",
        type: "tuple[]",
        components: [
          {name: "validator", type: "address"},
          {name: "untilEpochBanned", type: "uint256"},
          {name: "permanentlyBanned", type: "bool"},
        ],
      },
    ],
  },
  {
    name: "getPendingDelegatorDeposits",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [{name: "total", type: "uint256"}],
  },
  {
    name: "getPendingDelegatorWithdrawals",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [{name: "total", type: "uint256"}],
  },
  {
    name: "getPendingValidatorDeposits",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "total", type: "uint256"}],
  },
  {
    name: "getPendingValidatorWithdrawals",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "total", type: "uint256"}],
  },
  {
    name: "getValidatorDelegators",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "", type: "address[]"}],
  },
  {
    name: "getValidatorDelegatorsPaginated",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_startIndex", type: "uint256"},
      {name: "_pageSize", type: "uint256"},
    ],
    outputs: [{name: "", type: "address[]"}],
  },
  {
    name: "getValidatorQuarantineList",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address[]"}],
  },
  {
    name: "getValidatorsJoined",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_startIndex", type: "uint256"},
      {name: "_pageSize", type: "uint256"},
    ],
    outputs: [{name: "", type: "address[]"}],
  },
  {
    name: "idlenessBan",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_at", type: "uint256"},
      {name: "_until", type: "uint256"},
    ],
    outputs: [],
  },
  {
    name: "idlenessBanBatch",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "_validators", type: "address[]"},
      {name: "_quarantinedAt", type: "uint256"},
      {name: "_quarantinedUntil", type: "uint256"},
    ],
    outputs: [],
  },
  {
    name: "inflationEpoch",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "inflationInit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_inflationOnset", type: "uint256"}],
    outputs: [],
  },
  {
    name: "inflationReceive",
    type: "function",
    stateMutability: "payable",
    inputs: [{name: "_epoch", type: "uint256"}],
    outputs: [],
  },
  {
    name: "isDelegatorOfValidator",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_delegator", type: "address"},
    ],
    outputs: [{name: "", type: "bool"}],
  },
  {
    name: "isValidator",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "", type: "bool"}],
  },
  {
    name: "isValidatorBanned",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "", type: "bool"}],
  },
  {
    name: "setDeepthought",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_deepthought", type: "address"}],
    outputs: [],
  },
  {
    name: "setDelegatorMinimumStake",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_delegatorMinStake", type: "uint256"}],
    outputs: [],
  },
  {
    name: "setEpochMinDuration",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_epochMinDuration", type: "uint256"}],
    outputs: [],
  },
  {
    name: "setEpochMinDurationThreshold",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_epochMinDurationThreshold", type: "uint256"}],
    outputs: [],
  },
  {
    name: "setEpochZeroMinDuration",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_epochZeroMinDuration", type: "uint256"}],
    outputs: [],
  },
  {
    name: "setFinalizationPhase",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_finalizationPhase", type: "address"}],
    outputs: [],
  },
  {
    name: "setGen",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_gen", type: "address"}],
    outputs: [],
  },
  {
    name: "setIdlenessPhase",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_idlenessPhase", type: "address"}],
    outputs: [],
  },
  {
    name: "setMaxValidators",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_maxValidators", type: "uint256"}],
    outputs: [],
  },
  {
    name: "setReductionFactor",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_reductionFactor", type: "uint256"}],
    outputs: [],
  },
  {
    name: "setRevealingPhase",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_revealingPhase", type: "address"}],
    outputs: [],
  },
  {
    name: "setStakingInvariant",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_stakingInvariant", type: "address"}],
    outputs: [],
  },
  {
    name: "setTransactionFeesManager",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_transactionFeesManager", type: "address"}],
    outputs: [],
  },
  {
    name: "setUnbondingPeriods",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "_delegatorUnbondingPeriod", type: "uint256"},
      {name: "_validatorUnbondingPeriod", type: "uint256"},
    ],
    outputs: [],
  },
  {
    name: "setValidatorMinimumStake",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_validatorMinStake", type: "uint256"}],
    outputs: [],
  },
  {
    name: "setValidatorWeightParams",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "_alpha", type: "uint256"},
      {name: "_beta", type: "uint256"},
    ],
    outputs: [],
  },
  {
    name: "sharesOf",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "stakeOf",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_delegator", type: "address"},
      {name: "_validator", type: "address"},
    ],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "validatorBanDeterministic",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [],
  },
  {
    name: "validatorClaim",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "validatorDelegatorCount",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "validatorDeposit",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_index", type: "uint256"},
    ],
    outputs: [
      {name: "epoch_", type: "uint256"},
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "validatorDeposit",
    type: "function",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    name: "validatorDepositByEpoch",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_epoch", type: "uint256"},
    ],
    outputs: [
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "validatorDepositLen",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "validatorExit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_amount", type: "uint256"}],
    outputs: [],
  },
  {
    name: "validatorJoin",
    type: "function",
    stateMutability: "payable",
    inputs: [{name: "_operator", type: "address"}],
    outputs: [{name: "", type: "address"}],
  },
  {
    name: "validatorJoin",
    type: "function",
    stateMutability: "payable",
    inputs: [],
    outputs: [{name: "", type: "address"}],
  },
  {
    name: "validatorPrime",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [],
  },
  {
    name: "validatorQuarantine",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_at", type: "uint256"},
    ],
    outputs: [],
  },
  {
    name: "validatorQuarantineCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "validatorQuarantineRepeal",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [],
  },
  {
    name: "validatorSelection",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_seed", type: "bytes32"},
      {name: "_slot", type: "uint256"},
      {name: "_epoch", type: "uint256"},
      {name: "_txCreatedTimestamp", type: "uint256"},
      {name: "_number", type: "uint256"},
      {name: "_weighted", type: "bool"},
      {name: "_consumed", type: "address[]"},
    ],
    outputs: [
      {name: "leader_", type: "uint256"},
      {name: "validators_", type: "address[]"},
      {name: "penalized_", type: "address[]"},
    ],
  },
  {
    name: "validatorSelection",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_seed", type: "bytes32"},
      {name: "_slot", type: "uint256"},
      {name: "_txCreatedTimestamp", type: "uint256"},
      {name: "_number", type: "uint256"},
      {name: "_weighted", type: "bool"},
      {name: "_consumed", type: "address[]"},
    ],
    outputs: [
      {name: "leader_", type: "uint256"},
      {name: "validators_", type: "address[]"},
      {name: "penalized_", type: "address[]"},
    ],
  },
  {
    name: "validatorView",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          {name: "left", type: "address"},
          {name: "right", type: "address"},
          {name: "parent", type: "address"},
          {name: "eBanned", type: "uint256"},
          {name: "ePrimed", type: "uint256"},
          {name: "vStake", type: "uint256"},
          {name: "vShares", type: "uint256"},
          {name: "dStake", type: "uint256"},
          {name: "dShares", type: "uint256"},
          {name: "vDeposit", type: "uint256"},
          {name: "vWithdrawal", type: "uint256"},
          {name: "live", type: "bool"},
        ],
      },
    ],
  },
  {
    name: "validatorViewPrePrimed",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          {name: "left", type: "address"},
          {name: "right", type: "address"},
          {name: "parent", type: "address"},
          {name: "eBanned", type: "uint256"},
          {name: "ePrimed", type: "uint256"},
          {name: "vStake", type: "uint256"},
          {name: "vShares", type: "uint256"},
          {name: "dStake", type: "uint256"},
          {name: "dShares", type: "uint256"},
          {name: "vDeposit", type: "uint256"},
          {name: "vWithdrawal", type: "uint256"},
          {name: "live", type: "bool"},
        ],
      },
    ],
  },
  {
    name: "validatorViewPrimed",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          {name: "left", type: "address"},
          {name: "right", type: "address"},
          {name: "parent", type: "address"},
          {name: "eBanned", type: "uint256"},
          {name: "ePrimed", type: "uint256"},
          {name: "vStake", type: "uint256"},
          {name: "vShares", type: "uint256"},
          {name: "dStake", type: "uint256"},
          {name: "dShares", type: "uint256"},
          {name: "vDeposit", type: "uint256"},
          {name: "vWithdrawal", type: "uint256"},
          {name: "live", type: "bool"},
        ],
      },
    ],
  },
  {
    name: "validatorWithdrawal",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_index", type: "uint256"},
    ],
    outputs: [
      {name: "epoch_", type: "uint256"},
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "validatorWithdrawalByEpoch",
    type: "function",
    stateMutability: "view",
    inputs: [
      {name: "_validator", type: "address"},
      {name: "_epoch", type: "uint256"},
    ],
    outputs: [
      {
        name: "commit_",
        type: "tuple",
        components: [
          {name: "input", type: "uint256"},
          {name: "output", type: "uint256"},
          {name: "epoch", type: "uint256"},
          {name: "linkToNextCommit", type: "uint256"},
        ],
      },
    ],
  },
  {
    name: "validatorWithdrawalLen",
    type: "function",
    stateMutability: "view",
    inputs: [{name: "_validator", type: "address"}],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "validatorsCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "validatorsJoinedCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "uint256"}],
  },
  {
    name: "validatorsRoot",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{name: "", type: "address"}],
  },
] as const;

// Slash contract ABI for slashing events
export const SLASH_ABI = [
  {
    name: "SlashedFromIdleness",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: true},
      {name: "txId", type: "bytes32", indexed: false},
      {name: "epoch", type: "uint256", indexed: false},
      {name: "percentage", type: "uint256", indexed: false},
    ],
  },
  {
    name: "SlashEnacted",
    type: "event",
    inputs: [
      {name: "validator", type: "address", indexed: true},
      {name: "epoch", type: "uint256", indexed: false},
    ],
  },
] as const;
